language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
install:
  - npm install
script:
  - npm run build
after_success:
  - npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master